[package]
name = "update-assigned-numbers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["cargo"] }
convert_case = "0.7"
git2 = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
tempdir = "0.3"
